# Generated by Django 5.1.2 on 2024-11-27 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icecreamshop',
            old_name='shop_name',
            new_name='shopname',
        ),
    ]
